name: Releasability status

on:
  workflow_dispatch:

jobs:
  update_releasability_status:
    runs-on: ubuntu-latest
    name: Releasability status
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: SonarSource/gh-action_releasability/releasability-status@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
